/*
 * Description: Basic interface for dcmotor
 *
 * Created at: 20/09/2023
 *
 * Notes:
 * 	Timer for PWM motor control is tim3 (TIMER_HANDLE=htim3) (APB1@84MHz)
 * 	on CH1 & CH2
 *
 * 	PSC set @ 83 (84)
 * 	ARR set @ 999 (1000)
 *	Auto-reload preload: enabled
 *	Counter mode: up
 *
 *	GPIOs used: PA6 for CH1 (pwm1_dcmA1 in IDE)
 *		    PA7 for CH2 (pwm2_dcmA2 in IDE)
 */

#include "tim.h" // from autogenerated code
// #include "adc.h" // from autogenerated code
#include "motor_driver.h"

float dutycycle; // PWM dutycycle of currently active PWM timer channel

float voltage_sign = 1.0f; // 1 for positive, -1 for negative output voltage

// =============================================================================
// Function to initialize pwm GPIOs and set initial pwm to 0 DC
// =============================================================================
void dcm_init(void)
{
        // start timer
        HAL_TIM_PWM_Start(&TIMER_HANDLE, TIM_CHANNEL_1);
        HAL_TIM_PWM_Start(&TIMER_HANDLE, TIM_CHANNEL_2);
        // set initial dutycycle to zero on both channels
        // or use dcm_set_output_voltage(0); instead
        dcm_set_ch1_dutycycle(0); // ch1 to 0% duty cycle
        dcm_set_ch1_dutycycle(0); // ch2 to 0% duty cycle
}

// =============================================================================
// Function to zero the output voltage
// =============================================================================
void dcm_zero_output_voltage(void)
{
        dcm_set_ch1_dutycycle(0);
        dcm_set_ch2_dutycycle(0);
}

// =============================================================================
// Function to set output voltage in range [-12, 12]V
// =============================================================================
void dcm_set_output_volatage(float in_vol)
{
        if (in_vol >= 0) // ch1>0V, ch2=0V
        {
                if (in_vol > MAX_INPUT_VOLTAGE_POSITIVE) {
                        in_vol = MAX_INPUT_VOLTAGE_POSITIVE;
                }
                dutycycle = in_vol / MAX_INPUT_VOLTAGE_POSITIVE; // normalize
                dutycycle = dutycycle * 1000.0; // map to [0, 1000]
                dcm_set_ch2_dutycycle(0); // zero the other channel first
                dcm_set_ch1_dutycycle((uint16_t)dutycycle); // round ?
                voltage_sign = 1.0f;
        } else if (in_vol < 0) // ch1=0V, ch2>0V
        {
                if (in_vol < MAX_INPUT_VOLTAGE_NEGATIVE) {
                        in_vol = MAX_INPUT_VOLTAGE_NEGATIVE;
                }
                dutycycle = in_vol / MAX_INPUT_VOLTAGE_NEGATIVE;
                dutycycle = dutycycle * 1000.0;
                dcm_set_ch1_dutycycle(0);
                dcm_set_ch2_dutycycle((uint16_t)dutycycle);
                voltage_sign = -1.0f;
        }
}

// =============================================================================
// Function returns current output voltage setting calculated from the
// value of dutycycle
// =============================================================================
float dcm_get_output_voltage(void)
{
        float out =
                dutycycle / 1000.0f * MAX_INPUT_VOLTAGE_POSITIVE * voltage_sign;
        return out;
}

// =============================================================================
// Sets dutycycle for ch1&ch2 pwm
// dtc argument ranges between 0 and 1000
// =============================================================================
void dcm_set_ch1_dutycycle(uint16_t dtc)
{
        __HAL_TIM_SET_COMPARE(&TIMER_HANDLE, TIM_CHANNEL_1, dtc);
}

void dcm_set_ch2_dutycycle(uint16_t dtc)
{
        __HAL_TIM_SET_COMPARE(&TIMER_HANDLE, TIM_CHANNEL_2, dtc);
}
